name: Build and Scan
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      #- name: Install dependencies
      #  run: npm clean-install
      - name: Run Application
        run: nohup npm run start &
      - name: Run Hawkscan
        uses: stackhawk/hawkscan-action@v1.3.2
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
